version: '3.1'
services:
  ewm-stats-db:
    image: postgres:14-alpine
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-stats-service:
    build: ./stats-service/http-service/
    image: ewm-stats-service:v1.0.6
    container_name: ewm-stats-service
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - ewm-stats-db
    environment:
      - DB_HOST=ewm-stats-db
      - DB_PORT=5432
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - SR_PORT=9090
      - SR_DEBUG_PORT=9091
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9091"
    #      - TZ=Europe/Moscow

    #  ewm-main-db:
    #    image: postgres:14-alpine
    #    container_name: ewm-main-db
    #    ports:
    #      - "6542:5432"
    #    environment:
    #      - POSTGRES_DB=ewm-main
    #      - POSTGRES_USER=root
    #      - POSTGRES_PASSWORD=root
    #
    #  ewm-main-service:
    #    build: ./main-service/
    #    image: ewm-main-service:v1.0.0
    #    ports:
    #      - "8080:8080"
    #      - "8081:8081"
    #    depends_on:
    #      - ewm-main-db
    #      - DB_HOST=ewm-main-db
    #        - DB_PORT=5432
    #        - POSTGRES_DB=ewm-main-db
    #        - POSTGRES_USER=root
    #        - POSTGRES_PASSWORD=root
    #        - SR_PORT=8080
    #        - SR_DEBUG_PORT=8081
    #        - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8081"
    #      - TZ=Europe/Moscow