CREATE TABLE IF NOT EXISTS app (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,app varchar(128) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS stat (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,app_id bigint REFERENCES app(id) ON DELETE CASCADE NOT NULL,uri varchar(256) NOT NULL,ip varchar(15) NOT NULL CHECK(ip ~ ('^[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$')),requested timestamp WITHOUT TIME ZONE NOT NULL);

DELETE FROM app;
DELETE FROM stat;
ALTER TABLE stat ALTER id RESTART;
ALTER TABLE app ALTER id RESTART;